### ISSUE TITLE
buildlocaltools.cmd weird behaviour (at least on WinXP)

### ISSUE THREAD

**Issue by leecher1337** [stephanosio/NTOSBE#13]
See:
https://github.com/leecher1337/ntvdmx64/issues/76#issuecomment-591217642
https://github.com/leecher1337/ntvdmx64/issues/76#issuecomment-591526164

It seems that when making a call to a label in batch that weird behaviour can occur if the label is too far away from caller.
I only was able to fix this by moving the build command into a separate batch file that gets called instead of the label:

https://github.com/leecher1337/ntvdmx64/commit/45ecb5b4274373debcc07f25b82dd61cda8cd1e8

Any suggestions for a proper fix?

**Comment by stephanosio** [comment]
I think this could be a bug in NT 5.x `cmd`; not really sure of a workaround.

We could just move the "function" out to separate batch file: `buildlocalltool.cmd`, as you have already done.

**Comment by leecher1337** [comment]
I leave it to you to fix it so that you can name the seperate bactchfile according to your naming converntions. As soon as you resolved the issue, I can remove the workaround from my repository again.

**Comment by stephanosio** [comment]
@leecher1337 Updated the script. Please check if the issue is fixed.

**Comment by leecher1337** [comment]
@stephanosio SCript works. Please also take current pull request, as it fixes a severe problem in the nosrvbld script preventing a proper build, thanks.

**Comment by stephanosio** [comment]
@leecher1337 Sorry, I somehow missed that. I will look into it today.
